# Generated by Django 5.0.7 on 2024-08-15 18:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppSamuel', '0002_libro_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='año_de_publicacion',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(2099)]),
        ),
    ]
