# Generated by Django 5.0.7 on 2024-08-15 21:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppSamuel', '0003_alter_libro_año_de_publicacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='año_de_publicacion',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(2099)], verbose_name='Año de publicación'),
        ),
        migrations.AlterField(
            model_name='libro',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='libros/', verbose_name='Imagen'),
        ),
    ]
