# Generated by Django 5.0.7 on 2024-08-15 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppSamuel', '0008_alter_categoria_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='categoria',
            field=models.CharField(max_length=100, verbose_name='Categoría'),
        ),
    ]
