# Generated by Django 5.0.7 on 2024-08-08 19:03

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_avatar_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='avatar',
            unique_together={('user', 'imagen')},
        ),
    ]
